Action udpate

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -29,4 +29,14 @@ jobs:
     - name: Pack
       run: dotnet pack --no-build --configuration Release
     - name: Push Nuget Package
-      run: dotnet nuget push **/*.nupkg --source ${{ secrets.NUGET_PKG_URL }} --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
+      run: |
+        set -o pipefail
+        output=$(dotnet nuget push **/*.nupkg --source ${{ secrets.NUGET_PKG_URL }} --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate 2>&1)
+    
+        echo "$output"
+    
+        if echo "$output" | grep -q "already been pushed"; then
+          echo "❌ Package already exists. Failing the workflow."
+          echo "Please update the version of the package!"
+          exit 1
+        fi
